export enum AsyncStorageKey {
  APP_RUNNING_WORKOUT_STATE = 'APP_RUNNING_WORKOUT_STATE',
  APP_LANGUAGE = 'APP_LANGUAGE',
  APP_THEME = 'APP_THEME',
  APP_DISCLAIMER_AGREED = 'APP_DISCLAIMER_AGREED',
  LAST_DEFAULT_WORKOUT_CONFIG = 'LAST_DEFAULT_WORKOUT_CONFIG',
  HELD_WORKOUT_IDENTITY = 'HELD_WORKOUT_IDENTITY',
  /**
   * Setting items
   */
  WARMUP_DURATION_SETTING = 'WARMUP_DURATION_SETTING',
  COOLDOWN_DURATION_SETTING = 'COOLDOWN_DURATION_SETTING',
  COUNTDOWN_DURATION_SETTING = 'COUNTDOWN_DURATION_SETTING',
  TIMER_IN_BACKGROUND_SETTING = 'TIMER_IN_BACKGROUND_SETTING',
  VIBRATIONS_SETTING = 'VIBRATIONS_SETTING',
  SOUND_FEEDBACK_SETTING = 'SOUND_FEEDBACK_SETTING',
  VOICE_VARIANT_SETTING = 'VOICE_VARIANT_SETTING',
  CHARACTER_VARIANT_SETTING = 'CHARACTER_VARIANT_SETTING',
  PREMIUM_CHARACTER_ACTIVATIONS = 'PREMIUM_CHARACTER_ACTIVATIONS',
  SOUND_VARIANT_SETTING = 'SOUND_VARIANT_SETTING',
  STARS_RATED = 'STARS_RATED',
  FINISHED_WORKOUTS_COUNT = 'FINISHED_WORKOUTS_COUNT',
  WORKOUT_HISTORY = 'WORKOUT_HISTORY',
  IS_PREMIUM = 'IS_PREMIUM',
}
