export enum AsyncStorageKey {
  APP_RUNNING_WORKOUT_STATE = 'APP_RUNNING_WORKOUT_STATE',
  APP_LANGUAGE = 'APP_LANGUAGE',
  APP_THEME = 'APP_THEME',
  /**
   * Setting items
   */
  WARMUP_DURATION_SETTING = 'WARMUP_DURATION_SETTING',
  COOLDOWN_DURATION_SETTING = 'COOLDOWN_DURATION_SETTING',
  COUNTDOWN_DURATION_SETTING = 'COUNTDOWN_DURATION_SETTING',
  TIMER_IN_BACKGROUND_SETTING = 'TIMER_IN_BACKGROUND_SETTING',
  VIBRATIONS_SETTING = 'VIBRATIONS_SETTING',
  SOUND_FEEDBACK_SETTING = 'SOUND_FEEDBACK_SETTING',
  VOICE_VARIANT_SETTING = 'VOICE_VARIANT_SETTING',
  CHARACTER_VARIANT_SETTING = 'CHARACTER_VARIANT_SETTING',
  SOUND_VARIANT_SETTING = 'SOUND_VARIANT_SETTING',
}
