import { ImageURISource } from 'react-native';

export enum AppIllustration {
  sageFemale1 = 'sageFemale1',
  sageFemale2 = 'sageFemale2',
  sageFemale3 = 'sageFemale3',
  sageFemale4 = 'sageFemale4',
  sageFemale5 = 'sageFemale5',
  sageFemale6 = 'sageFemale6',
  sageFemale7 = 'sageFemale7',
  sageFemale8 = 'sageFemale8',
  sageFemale9 = 'sageFemale9',
  sageMale1 = 'sageMale1',
  sageMale2 = 'sageMale2',
  sageMale3 = 'sageMale3',
  sageMale4 = 'sageMale4',
  sageMale5 = 'sageMale5',
  sageMale6 = 'sageMale6',
  sageMale7 = 'sageMale7',
  sageMale8 = 'sageMale8',
  sageMale9 = 'sageMale9',
  shepherdsAroundFire = 'shepherdsAroundFire',
  ancientCityAtNight = 'ancientCityAtNight',
  ancientCityAtNightWithStairs = 'ancientCityAtNightWithStairs',
  ancientPillarsAtNight = 'ancientPillarsAtNight',
  ancientRocksAtNight = 'ancientRocksAtNight',
  bible = 'bible',
  earth = 'earth',
  hourglass = 'hourglass',
  roboticArm = 'roboticArm',
  universe = 'universe',
  pieceOfSilver = 'pieceOfSilver',
}

export const appIllustrations: Record<AppIllustration, ImageURISource> = {
  [AppIllustration.sageFemale1]: require('./images/avatars/female/sage_female_1.png'),
  [AppIllustration.sageFemale2]: require('./images/avatars/female/sage_female_2.png'),
  [AppIllustration.sageFemale3]: require('./images/avatars/female/sage_female_3.png'),
  [AppIllustration.sageFemale4]: require('./images/avatars/female/sage_female_4.png'),
  [AppIllustration.sageFemale5]: require('./images/avatars/female/sage_female_5.png'),
  [AppIllustration.sageFemale6]: require('./images/avatars/female/sage_female_6.png'),
  [AppIllustration.sageFemale7]: require('./images/avatars/female/sage_female_7.png'),
  [AppIllustration.sageFemale8]: require('./images/avatars/female/sage_female_8.png'),
  [AppIllustration.sageFemale9]: require('./images/avatars/female/sage_female_9.png'),
  [AppIllustration.sageMale1]: require('./images/avatars/male/sage_male_1.png'),
  [AppIllustration.sageMale2]: require('./images/avatars/male/sage_male_2.png'),
  [AppIllustration.sageMale3]: require('./images/avatars/male/sage_male_3.png'),
  [AppIllustration.sageMale4]: require('./images/avatars/male/sage_male_4.png'),
  [AppIllustration.sageMale5]: require('./images/avatars/male/sage_male_5.png'),
  [AppIllustration.sageMale6]: require('./images/avatars/male/sage_male_6.png'),
  [AppIllustration.sageMale7]: require('./images/avatars/male/sage_male_7.png'),
  [AppIllustration.sageMale8]: require('./images/avatars/male/sage_male_8.png'),
  [AppIllustration.sageMale9]: require('./images/avatars/male/sage_male_9.png'),
  [AppIllustration.shepherdsAroundFire]: require('./images/backgrounds/shepherds_around_fire.png'),
  [AppIllustration.ancientCityAtNight]: require('./images/backgrounds/ancient_city_at_night.png'),
  [AppIllustration.ancientCityAtNightWithStairs]: require('./images/backgrounds/ancient_city_at_night_with_stairs.png'),
  [AppIllustration.ancientPillarsAtNight]: require('./images/backgrounds/ancient_pillars_at_night.png'),
  [AppIllustration.ancientRocksAtNight]: require('./images/backgrounds/ancient_rocks_at_night.png'),
  [AppIllustration.bible]: require('./images/questions/bible.png'),
  [AppIllustration.earth]: require('./images/questions/earth.png'),
  [AppIllustration.hourglass]: require('./images/questions/hourglass.png'),
  [AppIllustration.roboticArm]: require('./images/questions/robotic_arm.png'),
  [AppIllustration.universe]: require('./images/questions/universe.png'),
  [AppIllustration.pieceOfSilver]: require('./images/piece_of_silver.png'),
};

export enum AppAnimation {
  thinkingOwl = 'thinking_owl',
  loader = 'loader',
  confetti = 'confetti',
}
